remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

sass:
  style: compressed

# Voeg custom CSS toe
include:
  - assets/css/custom.css

title: Hoogbegaafdheid Overzicht
description: Antwoorden op vragen over hoogbegaafdheid

menu:
  - name: Home
    link: /
  - name: Over Hoogbegaafdheid Overzicht
    link: /about/

